version: '3.8'

services:
  trackfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trackfolio_app
    restart: unless-stopped
    ports:
      - "6005:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - trackfolio_network

networks:
  trackfolio_network:
    driver: bridge

